apiVersion: v1
kind: Service
metadata:
   name: java-service
   labels:
     app: java-app
spec:
   type: NodePort
   ports:
   - port: 2206
   selector:
      app: java-app
   
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: java-deployment
   labels:
     app: java-app
spec:
  selector:
     matchLabels:
         app: java-app
  template:
     metadata:
        labels:
          app: java-app
     spec:
       containers:
       - name: java-container
         image: docker202020/java:latest
         ports:
         - containerPort: 2206
---
apiVersion: networking.k8s.io/v1beta1 
kind: Ingress
metadata:
  name: java-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
 rules:
 - host: java-connect.info
   http:
     paths:
     - path: /|/(.+)
       backend:
         serviceName: java-service
         servicePort: 2206
