
# Corpus Table Creation
CREATE TABLE CORPUS (KEYWORD varchar(256) NOT NULL, RELEVANCE double NOT NULL, FREQUENCY int NOT NULL, CAT_NAME varchar(40), 
TENANT_ID bigint NOT NULL,CONSTRAINT CORPUS_unique_index UNIQUE (KEYWORD, CAT_NAME, TENANT_ID)) ENGINE=InnoDB DEFAULT CHARSET=latin1;

# Corpus Default Table Creation
CREATE TABLE CORPUS_DEFAULT 
(
   KEYWORD varchar(256) NOT NULL, 
   RELEVANCE double NOT NULL,  
   FREQUENCY int NOT NULL, 
   CAT_NAME varchar(40),  
   CONSTRAINT CORPUS_unique_index UNIQUE (KEYWORD, CAT_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
