FROM  inmbzp7148.in.dst.ibm.com:5000/ubuntu:69

MAINTAINER <sureakum@in.ibm.com>
USER root

# add our user and group first to make sure their IDs get assigned consistently, regardless of whatever dependencies get added
# RUN groupadd -r mysql && useradd -r -g mysql mysql
RUN groupadd -r mysql --gid=999 && useradd -r -g mysql --uid=999 mysql

# add gosu for easy step-down from root
ENV GOSU_VERSION 1.7

## for apt to be noninteractive
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

ENV MYSQL_MAJOR 5.7
ENV MYSQL_VERSION 5.7

RUN 	echo "tzdata tzdata/Areas select Asia" > /tmp/preseed.txt; \
	echo "tzdata tzdata/Zones/Asia select Kolkata" >> /tmp/preseed.txt; \
	debconf-set-selections /tmp/preseed.txt && \
	rm /etc/timezone && \
    	rm /etc/localtime \
	&& apt-get update && apt-get install -y --no-install-recommends ca-certificates wget  tzdata \
	&& wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)" \
	&& wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc" \
	&& export GNUPGHOME="$(mktemp -d)" \
	&& gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
	&& gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
	&& rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc \
	&& chmod +x /usr/local/bin/gosu \
	&& gosu nobody true \
	&& apt-get purge -y --auto-remove \
	&& mkdir /docker-entrypoint-initdb.d \
	&& apt-get install -y perl pwgen --no-install-recommends  
RUN 	apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys A4A9406876FCBD3C456770C88C718D3B5072E1F5 \
	&& echo "deb http://repo.mysql.com/apt/ubuntu/ xenial mysql-${MYSQL_MAJOR}" > /etc/apt/sources.list.d/mysql.list \
	&& { \
		echo mysql-community-server mysql-community-server/data-dir select ''; \
		echo mysql-community-server mysql-community-server/root-pass password ''; \
		echo mysql-community-server mysql-community-server/re-root-pass password ''; \
		echo mysql-community-server mysql-community-server/remove-test-db select false; \
	} | debconf-set-selections \
	&& apt-get update && apt-get install -y --allow-authenticated mysql-server && rm -rf /var/lib/apt/lists/* \ 
	&& rm -rf /var/lib/mysql && mkdir -p /var/lib/mysql /var/run/mysqld \
	&& chown -R mysql:mysql /var/lib/mysql /var/run/mysqld \
	&& chmod 777 /var/run/mysqld \
	&& sed -Ei 's/^(bind-address|log)/#&/' /etc/mysql/mysql.conf.d/mysqld.cnf \
	&& echo 'skip-host-cache\nskip-name-resolve' | awk '{ print } $1 == "[mysqld]" && c == 0 { c = 1; system("cat") }' /etc/mysql/mysql.conf.d/mysqld.cnf > /tmp/mysqld.cnf \
	&& mv /tmp/mysqld.cnf /etc/mysql/mysql.conf.d/mysqld.cnf

# VOLUME /var/lib/mysql

ENV MSDATA_MP /mysqldata
ENV MSDATA_PATH /mysqldata/mysql
ENV MSUSER mysql
ENV MSGRP mysql

COPY docker-entrypoint.sh /usr/local/bin/

RUN ln -s usr/local/bin/docker-entrypoint.sh /entrypoint.sh # backwards compat && \
	cp /usr/share/zoneinfo/Asia/Calcutta /etc/localtime \
    && echo "Asia/Calcutta  " > /etc/timezone

#USER mysql

ENTRYPOINT ["docker-entrypoint.sh"]

EXPOSE 3306

#COPY	script.sh  /opt/ 
COPY	VD-DDLScripts.sql /docker-entrypoint-initdb.d/

CMD ["mysqld"]

