
CREATE SCHEMA REPORTS;

CREATE TABLE IF NOT EXISTS `TENANT` (
  `TENANT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TENANT_NAME` varchar(100) NOT NULL,
  `SOC_FUNCTIONAL_ID` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`TENANT_ID`),
  UNIQUE KEY `TENANT_NAME` (`TENANT_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `ENGAGEMENT` (
  `ENGAGEMENT_ID` bigint(20) NOT NULL,
  `ENGAGEMENT_NAME` varchar(200) NOT NULL,
  `ENGAGEMENT_START_DT` datetime NOT NULL,
  `ENGAGEMENT_END_DT` datetime NOT NULL,
  `ENGAGEMENT_OWNING_COUNTRY` varchar(100) NOT NULL,
  `TENANT_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ENGAGEMENT_ID`),
  UNIQUE KEY `ENGAGEMENT_NAME` (`ENGAGEMENT_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE IF NOT EXISTS `CATEGORY` (
  `CAT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CAT_NAME` varchar(40) NOT NULL,
  `TENANT_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`CAT_ID`),
  UNIQUE KEY `CATEGORY_unique_index` (`CAT_NAME`,`TENANT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE IF NOT EXISTS `NLC_SERVICE_CREDENTIALS` (
  `NLC_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NLC_NAME` varchar(50) NOT NULL,
  `NLC_USERNAME` varchar(100) NOT NULL,
  `NLC_PASSWORD` varchar(100) NOT NULL,
  PRIMARY KEY (`NLC_ID`),
  UNIQUE KEY `NLC_NAME` (`NLC_NAME`),
  UNIQUE KEY `NLC_USERNAME` (`NLC_USERNAME`),
  UNIQUE KEY `NLC_PASSWORD` (`NLC_PASSWORD`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `SERVICE_TOOLS` (
  `SERVICE_TOOL_NAME` varchar(100) NOT NULL,
  `ACCESS_KEY` varchar(100) NOT NULL,
  `STATUS` int(11) NOT NULL,
  `COMMENTS` varchar(100) NOT NULL,
  UNIQUE KEY `SERVICE_TOOL_NAME` (`SERVICE_TOOL_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE IF NOT EXISTS `WATSON_MODEL` (
  `TENANT_ID` bigint(20) NOT NULL,
  `MODEL_ID` varchar(100) NOT NULL,
  `NLC_ID` bigint(20) NOT NULL,
  UNIQUE KEY `MODEL_ID` (`MODEL_ID`),
  CONSTRAINT `WATSON_MODEL_fk1` FOREIGN KEY (`NLC_ID`) REFERENCES `NLC_SERVICE_CREDENTIALS` (`NLC_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS REPORTS.`TICKETS` 
(
  SL_NO bigint NOT NULL AUTO_INCREMENT, 
  TICKET_ID varchar(12) NOT NULL, 
  TICKET_SOURCE varchar(20) NOT NULL, 
  TICKET_TYPE varchar(10) NOT NULL, 
  TENANT varchar(256) NOT NULL, 
  ENGAGEMENT varchar(256) NOT NULL, 
  CATEGORY varchar(100) NOT NULL, 
  ASSIGNEE varchar(150), 
  ASSIGNED_TIME datetime, 
  REMARKS varchar(512),
  CREATED_BY VARCHAR(100),
  CREATED_ON DATETIME, 
  PRIMARY KEY (SL_NO)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE NLU_SERVICE_CREDENTIALS 
(
     NLU_ID bigint NOT NULL AUTO_INCREMENT, 
     NLU_NAME varchar(50) NOT NULL, 
     NLU_USERNAME varchar(100) NOT NULL, 
     NLU_PASSWORD varchar(100) NOT NULL, 
     PRIMARY KEY (NLU_ID), 
     CONSTRAINT NLU_NAME UNIQUE (NLU_NAME), 
     CONSTRAINT NLU_USERNAME UNIQUE (NLU_USERNAME), 
     CONSTRAINT NLU_PASSWORD UNIQUE (NLU_PASSWORD)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE NOTIFICATION 
(
     COUNTRY varchar(100), 
     INTRANETID varchar(100), 
     MODIFIED_BY varchar(100), 
     MODIFIED_ON datetime
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE WATSON_MODEL_DEFAULT 
(
   MODEL_ID varchar(100), 
   NLC_ID bigint NOT NULL, 
   CONSTRAINT MODEL_ID UNIQUE (MODEL_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE CATEGORY_DEFAULT 
(  
   CAT_ID bigint NOT NULL AUTO_INCREMENT, 
   CAT_NAME varchar(40) NOT NULL, 
   PRIMARY KEY (CAT_ID),
   CONSTRAINT CATEGORY_unique_index UNIQUE (CAT_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `ENGAGEMENT` ADD CONSTRAINT `ENGAGEMENT_fk0` FOREIGN KEY (`TENANT_ID`) REFERENCES `TENANT`(`TENANT_iD`);
ALTER TABLE `CATEGORY` ADD CONSTRAINT `CATEGORY_fk0` FOREIGN KEY (`TENANT_ID`) REFERENCES `TENANT`(`TENANT_ID`);
ALTER TABLE `WATSON_MODEL` ADD CONSTRAINT `WATSON_MODEL_fk0` FOREIGN KEY (`TENANT_ID`) REFERENCES `TENANT`(`TENANT_ID`);
ALTER TABLE `WATSON_MODEL` ADD CONSTRAINT `WATSON_MODEL_fk_NLC` FOREIGN KEY (`NLC_ID`) REFERENCES `NLC_SERVICE_CREDENTIALS`(`NLC_ID`);
ALTER TABLE REPORTS.TICKETS ADD COLUMN IS_NOTIFICATION_SENT INTEGER DEFAULT 0;
ALTER TABLE TENANT ADD COLUMN HISTORICAL_DATA_STATUS INTEGER DEFAULT 2;
ALTER TABLE WATSON_MODEL DROP INDEX MODEL_ID;

INSERT INTO NLC_SERVICE_CREDENTIALS VALUES (DEFAULT,'vd-nlc-prod-1','cf362151-7cfa-46c3-ba69-c140e7b6701d','GI7iUtksNoMj');
INSERT INTO SERVICE_TOOLS (SERVICE_TOOL_NAME, ACCESS_KEY, STATUS, COMMENTS) VALUES ('ICD', 'ZGhtb25pdG9AaW4uaWJtLmNvbTpkaGZsQDEyMw==', 1, 'Admin Entry');
INSERT INTO NLU_SERVICE_CREDENTIALS VALUES (DEFAULT,'vd-nlu-prod','796a4b3d-0b50-411b-a34b-5e1436f1a9bf','2bbyqaaz4hFf');



