# Default values for my-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker202020/myrepo
  tag: v1
  pullPolicy: IfNotPresent


service:
  type: ClusterIP
  port: 3306


persistence:
  enabled: true
  accessMode: ReadWriteMany
  size: 10Gi

resources:
  limits:
   cpu: 1
   memory: 2Gi

MYSQL_ROOT_PASSWORD:
  value: admin          

MYSQL_DATABASE:
  value: sample
